version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=user@domain.co.za
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=user@domain.co.za
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.domain.co.za
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=email@domain.co.za
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=<password>
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY=2
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=<NAME-OF-SERVER>
      - WATCHTOWER_SCHEDULE=0 0 0 */1 * *
      - TZ=Africa/Johannesburg
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
